# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e59f62bc326df6bdb9df4aac5d81ad81cb5a31cd5074619c04eb5db7f6271e9274a7e34ba580633d568a985d659c5e4ca82a211d0a89e1e9e9656a15674b38d5

test:
  secret_key_base: ea6ab4425a065f2af61cd2d326bcaa1ecbe90278d9368ed1d8bcc6a03c47e2459633d28ce6eabed46c8cbf42345abc5bb2f162e1427a9d6b3fb456df5bafd933

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
